stages:
  union_tsv_files:
    cmd: python -m src.utils.union_tsv_files --paths data/entity_relation_extraction_multilingual/pl_corpora_test.tsv
      data/entity_relation_extraction_multilingual/pl_corpora_train.tsv --output_tsv
      data/edc_baseline/corpora.tsv
    wdir: ../..
    deps:
    - data/entity_relation_extraction_multilingual/pl_corpora_test.tsv
    - data/entity_relation_extraction_multilingual/pl_corpora_train.tsv
    - src/utils/union_tsv_files.py
    outs:
    - data/edc_baseline/corpora.tsv
  precheck_corpora:
    cmd: python -m src.edc_baseline.precheck_corpora --tsv_path data/edc_baseline/corpora.tsv
      --output_path data/edc_baseline/corpora_cleaned.tsv --verbose
    wdir: ../..
    deps:
    - data/edc_baseline/corpora.tsv
    - src/edc_baseline/precheck_corpora.py
    outs:
    - data/edc_baseline/corpora_cleaned.tsv
  create_dataset_file:
    params:
      - pipelines/edc_baseline/params.yaml:
        - dataset_subsample_size
        - dataset_subsample_seed
    cmd: python -m src.edc_baseline.create_dataset_file --tsv_path data/edc_baseline/corpora_cleaned.tsv
      --output_path data/edc_baseline/dataset.txt --verbose --reference_output_path data/edc_baseline/reference.txt
      --subsample_size ${dataset_subsample_size} --subsample_seed ${dataset_subsample_seed}
    wdir: ../..
    deps:
    - data/edc_baseline/corpora_cleaned.tsv
    - src/edc_baseline/create_dataset_file.py
    - src/edc_baseline/create_reference_file.py
    outs:
    - data/edc_baseline/dataset.txt
    - data/edc_baseline/reference.txt
  create_fewshot_examples:
    params:
      - pipelines/edc_baseline/params.yaml:
        - random_state
        - sample_size
    cmd: python -m src.edc_baseline.create_fewshot_examples 
      --dataset_path data/edc_baseline/dataset.txt
      --schema_path data/edc_baseline/schema.csv --reference_path data/edc_baseline/reference.txt 
      --oie_fewshot_output_path data/edc_baseline/oie_few_shot_examples.txt
      --sd_fewshot_output_path data/edc_baseline/sd_few_shot_examples.txt
      --random_state ${random_state}
      --sample_size ${sample_size}
    wdir: ../..
    deps:
    - data/edc_baseline/dataset.txt
    - data/edc_baseline/schema.csv
    - data/edc_baseline/reference.txt
    - src/edc_baseline/create_fewshot_examples.py
    outs:
    - data/edc_baseline/oie_few_shot_examples.txt
    - data/edc_baseline/sd_few_shot_examples.txt
  extract_relations:
    params:
      - pipelines/edc_baseline/params.yaml:
        - debug_llm
    cmd: papermill --log-output --stdout-file notebooks/extract_relations/local_papermill_logs.txt --log-level INFO --parameters DEBUG ${debug_llm} notebooks/extract_relations/langgraph_extract_relations.ipynb notebooks/extract_relations/langgraph_extract_relations_output.ipynb
    wdir: ../..
    deps:
    - notebooks/extract_relations/langgraph_extract_relations.ipynb
    - data/edc_baseline/dataset.txt
    - data/edc_baseline/schema.csv
    - src/extractors/extractor.py
    - src/polish_kg_langchain/State.py
    - src/polish_kg_langchain/InstructionStripper.py
    - src/polish_kg_langchain/Graph.py
    - src/polish_kg_langchain/create_chat_huggingface.py
    - src/polish_kg_langchain/ConfigSchema.py
    - src/polish_kg_langchain/__init__.py
    - src/polish_kg_langchain/nodes/validate_did_refuse_to_answer.py
    - src/polish_kg_langchain/nodes/validate_did_format_correctly.py
    - src/polish_kg_langchain/nodes/print_value.py
    - src/polish_kg_langchain/nodes/noop.py
    - src/polish_kg_langchain/nodes/extract_triple.py
    - src/polish_kg_langchain/nodes/extract_triple_bielik.py
    - src/polish_kg_langchain/nodes/correct_triple.py
    - src/polish_kg_langchain/nodes/__init__.py
    outs:
    - notebooks/extract_relations/langgraph_extract_relations_output.ipynb
    - data/edc_baseline/errors.json
    - data/edc_baseline/extracted_relations.json
    - notebooks/extract_relations/local_papermill_logs.txt
    - data/edc_baseline/graph_states.pkl
  prepare_for_evaluation:
    params:
      - pipelines/edc_baseline/params.yaml:
        - debug_llm
    cmd: python -m src.evaluation.parsing --extracted_relations_json data/edc_baseline/extracted_relations.json --output_refs_xml data/edc_baseline/refs.xml --output_cands_xml data/edc_baseline/cands.xml --reference_txt data/edc_baseline/reference.txt --DEBUG ${debug_llm}
    wdir: ../..
    deps: 
    - data/edc_baseline/extracted_relations.json
    - data/edc_baseline/reference.txt
    - src/evaluation/parsing.py
    - src/evaluation/regex_matching.py
    outs:
    - data/edc_baseline/refs.xml
    - data/edc_baseline/cands.xml
  evaluate:
    cmd: python src/evaluation/Evaluation_script_json.py data/edc_baseline/refs.xml data/edc_baseline/cands.xml data/edc_baseline/evaluation_results.json data/edc_baseline/evaluation_results_per_line.json
    wdir: ../..
    deps:
    - data/edc_baseline/refs.xml
    - data/edc_baseline/cands.xml
    - src/evaluation/Evaluation_script_json.py
    outs:
    - data/edc_baseline/evaluation_results.json
    - data/edc_baseline/evaluation_results_per_line.json
  generate_report:
    params:
        - pipelines/edc_baseline/params.yaml:
          - llm
    cmd: papermill --parameters model_name ${llm} notebooks/reports/report_vanilla_relation_extraction.ipynb notebooks/reports/report_vanilla_relation_extraction_output.ipynb
    wdir: ../..
    deps:
    - notebooks/reports/report_vanilla_relation_extraction.ipynb
    - data/edc_baseline/evaluation_results.json
    - data/edc_baseline/evaluation_results_per_line.json
    - data/edc_baseline/cands.xml
    - data/edc_baseline/refs.xml
    outs:
    - notebooks/reports/report_vanilla_relation_extraction_output.ipynb
    metrics:
    - data/edc_baseline/metrics.json
    plots:
    - data/edc_baseline/report_total_found.png
    - data/edc_baseline/report_total_f1.png