# parameters used by create_dataset_file
dataset_subsample_size: 1.0 # set this to 1.0 to use the full dataset
dataset_subsample_seed: 11

# parameters used by create_fewshot_examples
sample_size: 6
random_state: 11



# parameters used by extract_relations, prepare_for_evaluation
llm: "o3-mini" # speakleash/Bielik-11B-v2.2-Instruct or dummy or CYFRAGOVPL/Llama-PLLuM-8B-instruct or o3-mini
debug_llm: 1 # true/false
