services:
  python:
    tty: true
    image: polish-kg-python:0.2
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
    volumes:
      - .:/app:rw
    env_file:
      - .env
    entrypoint: ["/app/docker-entrypoint-webserver.sh"]
    # uncomment the following lines to enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]