services:
  python:
    tty: true
    image: staszekm/polish-kg-python:0.5-webserver
    env_file:
      - .env
    # uncomment the following lines to enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]